//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace esquivel.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class esquivelEntities : DbContext
    {
        public esquivelEntities()
            : base("name=esquivelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
    
        public virtual ObjectResult<SP_LISTAR_PRODUCTOS_Result> SP_LISTAR_PRODUCTOS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LISTAR_PRODUCTOS_Result>("SP_LISTAR_PRODUCTOS");
        }
    
        public virtual int SP_GUARDAR_PRODUCTO(string nompro, Nullable<int> precio)
        {
            var nomproParameter = nompro != null ?
                new ObjectParameter("nompro", nompro) :
                new ObjectParameter("nompro", typeof(string));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("precio", precio) :
                new ObjectParameter("precio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GUARDAR_PRODUCTO", nomproParameter, precioParameter);
        }
    
        public virtual int SP_MODIFICAR_PRODUCTO(Nullable<int> codpro, string nompro, Nullable<int> precio)
        {
            var codproParameter = codpro.HasValue ?
                new ObjectParameter("codpro", codpro) :
                new ObjectParameter("codpro", typeof(int));
    
            var nomproParameter = nompro != null ?
                new ObjectParameter("nompro", nompro) :
                new ObjectParameter("nompro", typeof(string));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("precio", precio) :
                new ObjectParameter("precio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MODIFICAR_PRODUCTO", codproParameter, nomproParameter, precioParameter);
        }
    
        public virtual int SP_ELIMINAR_PRODUCTO(Nullable<int> codpro)
        {
            var codproParameter = codpro.HasValue ?
                new ObjectParameter("codpro", codpro) :
                new ObjectParameter("codpro", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ELIMINAR_PRODUCTO", codproParameter);
        }
    }
}
